Adding new digit validation method
hurbcom/angular-boleto pull request #8
Opened 2022-01-13 19:06 UTC by felipepestana

# Tarefa / *user history*

[SP-1311](https://hurbcom.atlassian.net/jira/software/c/projects/SP/boards/12?modal=detail&selectedIssue=SP-1311)

Hoje o sistema de fornecedores/recebíveis possui uma validação de alguns dados do boleto digitável pelo parceiro. Porém existem casos onde o parceiro digita um outro dígito errado e isso só é detectado após o SAP solicitar o pagamento da fatura.

Precisamos complementar a validação existente para identificar os erros o quanto antes.

# O quê esse PR faz?

Adiciona um novo método para validar o dígito verificador geral nos números de boleto.

## - Antes

O dígito verificador geral não estava sendo validado.

## - Depois

O dígito verificador geral passa a ser validado e, caso este esteja errado, é retornado uma mensagem de erro.

## - Como testar?

Acessar a área do fornecedor usando um fornecedor com a opção de pagamento como faturado e requisitar a geração de uma nova fatura usando vouchers em aberto. Preencher o campo de "número boleto" com informações válidas e inválidas e verificar se algum erro é retornado e qual a mensagem associada.

## - TODOs
- [ ] Testes
- [ ] Documentação
- [ ] Débito técnico

# Criou o RC a partir da master?
- [X] Sim
- [ ] Não

# Precisa de migration?
- [ ] Sim
- [X] Não

# Risks
Nenhum risco mapeado

# PS: Não se esqueça de enviar a PR para master após o código estar estável em produção!!

2022-01-13 19:48 UTC, vbandeira-hurb approved these changes

2022-01-13 21:12 UTC, viollarr approved these changes

2022-01-13 22:18 UTC, bernardolm requested changes
Uma alteração sensível assim pede testes unitários que não vi nas modificações.

2022-01-13 22:20 UTC, bernardolm commented
Após as mudanças os testes unitários foram executados e sem apresentar falhas?

2022-01-14 13:57 UTC, felipepestana commented
> Uma alteração sensível assim pede testes unitários que não vi nas modificações.

Testes atualizados para considerar o novo método de validação (inclusive consertando as falhas)

2022-02-01 14:32 UTC, merged